
<?php

 function test_menu(){
   $items['dna'] = array(
     'title' => "Calculate DNA",
     'type' => MENU_NORMAL_ITEM,
     'access callback' => TRUE,
     'page callback' => 'drupal_get_form',
     'page arguments' => array('test_form'),
   );
   $items['test_success_page'] = array(
     'title' => "Dna Success",
     'type' => MENU_CALLBACK,
     'access callback' => TRUE,
     'page callback' => 'test_success',
   );
   return $items;
 }
 function test_form(){
   $form['dna'] = array(
     '#title' => 'DNA',
     '#type' => 'textfield',
     '#description' => t('Enter DNA'),
   );

   $form['submit'] = array(
     '#type' => 'submit',
     '#value' => 'Calculate',
   );
   return $form;
 }
 function test_form_submit($form, &$form_state){
    $dna = $form_state['values']['dna'];
    $Dna = str_split($dna);
    $result = "";
    for($i = 0; $i < count($Dna); $i++){
      if($Dna[$i] == "A"){
         $result .= "T";
      }else if($Dna[$i] == "T"){
        $result .= "A";
      }else if($Dna[$i] == "G"){
        $result .= "C";
      }else if($Dna[$i] == "C"){
        $result .= "G";
      }else{
        $result = "<p>Thats not DNA</p>";
      }
    }
    // return $result;
    $_SESSION['dna'] = $result;
    $form_state['redirect'] = 'test_success_page';
  }

  function test_success(){
   $result = $_SESSION['dna'];
   return $result;
 }

 function dna_form_test($input){
   $Dna = str_split($input);
   $result = "";
   for($i = 0; $i < count($Dna); $i++){
     if($Dna[$i] == "A"){
        $result .= "T";
     }else if($Dna[$i] == "T"){
       $result .= "A";
     }else if($Dna[$i] == "G"){
       $result .= "C";
     }else if($Dna[$i] == "C"){
       $result .= "G";
     }else{
       $result = '<p>Thats not DNA</p>';
     }
   }
   return $result;
   $_SESSION['dna'] = $result;
   $form_state['redirect'] = 'test_success_page';
 }
